# Generated by Django 3.2.8 on 2021-11-23 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordev', '0002_alter_page_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='pagecategory',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='описание'),
        ),
    ]
