# Generated by Django 3.2.8 on 2021-12-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordev', '0003_auto_20211123_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='is_boxed',
            field=models.BooleanField(db_index=True, default=False, verbose_name='закрепленный'),
        ),
    ]
