# Generated by Django 3.2.8 on 2021-12-01 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordev', '0004_page_is_boxed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='краткое содержание'),
        ),
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(null=True, verbose_name='текст'),
        ),
    ]
