# Generated by Django 3.2.8 on 2021-12-01 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fordev', '0005_auto_20211201_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='text',
            field=models.TextField(blank=True, null=True, verbose_name='текст'),
        ),
    ]
