# Generated by Django 3.2.8 on 2022-05-10 20:04

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Тег')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активный')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Тег',
                'ordering': ['-is_active', '-created'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='Заголовок')),
                ('text', models.TextField(blank=True, verbose_name='Текст заметки')),
                ('full_text', models.TextField(blank=True, verbose_name='Полное содержание')),
                ('created', models.DateTimeField(default=datetime.datetime.now, verbose_name='Дата и время создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_favorites', models.BooleanField(db_index=True, default=False, verbose_name='В избранном')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активный')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='notes.Tag', verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Заметка',
                'verbose_name_plural': 'Заметки',
                'ordering': ['-is_active', '-is_favorites', '-created'],
            },
        ),
    ]
