# Generated by Django 3.2.8 on 2022-04-09 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.Tag', verbose_name='Тэг'),
        ),
    ]
