# Generated by Django 3.2.8 on 2021-11-18 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_favorites',
            field=models.BooleanField(db_index=True, default=True, verbose_name='В избранном'),
        ),
    ]
