<<<<<<< HEAD
# Generated by Django 3.2.9 on 2021-11-19 16:06
=======
# Generated by Django 3.2.8 on 2021-11-18 12:24
>>>>>>> df3149cb4008b7be02858b55d4b38177c5ffd7cf

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_note_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='is_favorites',
<<<<<<< HEAD
            field=models.BooleanField(db_index=True, default=False, verbose_name='В избранном'),
=======
            field=models.BooleanField(db_index=True, default=True, verbose_name='В избранном'),
>>>>>>> df3149cb4008b7be02858b55d4b38177c5ffd7cf
        ),
    ]
