# Generated by Django 3.2.8 on 2021-11-18 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_is_favorites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активный'),
        ),
    ]
