# Generated by Django 3.2.9 on 2022-04-27 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20220427_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tests',
        ),
    ]
