# Generated by Django 3.2.9 on 2022-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_remove_note_tests'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.Tag', verbose_name='Тэги'),
        ),
    ]
