# Generated by Django 3.2.8 on 2021-11-21 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20211118_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_active', '-is_favorites', '-update', '-created'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
