# Generated by Django 3.2.9 on 2022-04-27 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_alter_note_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.TextField(blank=True, verbose_name='Тэги'),
        ),
    ]
