# Generated by Django 3.2.9 on 2022-04-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20220427_1353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='tags',
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.Tag', verbose_name='Тэги'),
        ),
    ]
