# Generated by Django 3.2.9 on 2022-04-27 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20220427_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notes.Tag', verbose_name='Тэг'),
        ),
    ]
