# Generated by Django 3.2.8 on 2021-12-01 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20211130_0750'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-is_active', '-is_favorites', '-created'], 'verbose_name': 'Заметка', 'verbose_name_plural': 'Заметки'},
        ),
    ]
