# Generated by Django 3.2.8 on 2021-12-01 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20211201_1146'),
        ('notes', '0008_alter_note_options'),
    ]

    operations = [
    ]
