# Generated by Django 3.2.8 on 2022-02-02 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_merge_0007_auto_20211201_1146_0008_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, verbose_name='Дата и время создания'),
        ),
    ]
