# Generated by Django 3.2.8 on 2021-11-09 17:34

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('staff', models.BooleanField(default=False, verbose_name='Сотрудник')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный')),
                ('admin', models.BooleanField(default=False, verbose_name='Администратор')),
                ('timestamp', models.DateTimeField(verbose_name='Создан')),
            ],
            options={
                'verbose_name': ('Пользователь',),
                'verbose_name_plural': ('Пользователи',),
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
